name: Add new challenge

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Git
        run: |
          git config user.name "${{ github.triggering_actor }}"
          git config user.email "${{ vars.NOREPLY_EMAIL }}"

      - name: Add new challenge
        run: |
          bun install
          bun ./scripts/add.ts

