name: Add new challenge(s)

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Git
        run: |
          git config user.name "${{ github.triggering_actor }}"
          git config user.email "${{ vars.NOREPLY_EMAIL }}"

      - name: Add new challenge(s)
        run: |
          bun install
          bun ./scripts/add.ts
