name: Update README.org.md

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * 0

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      updated: ${{ steps.update_readme.outputs.updated }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Git
        run: |
          git config user.name "${{ github.triggering_actor }}"
          git config user.email "${{ vars.NOREPLY_EMAIL }}"

      - name: Update README.org.md
        id: update_readme
        run: |
          bun install
          bun ./scripts/readme.ts

  add:
    needs: main
    if: ${{ needs.main.outputs.updated == 'true' }}
    uses: lvjiaxuan/type-challenges/.github/workflows/add.yml@master
